### PR TITLE
Create script installer

### PR DESCRIPTION
**Pull request by showcheap**
Please create script installer for popular CMS like  Wordpress, Drupal, Etc.

I'm trying to create plugin like that, but it still very bad. Because i'm not master on python language.

### CODE REVIEW

**Comment by kshitijsalgunan** [comment]
I am also interested in such a one click installer. Also, no other free control panels have this feature.
@showcheap :- Is your script working? How to install it?

**Comment by LukevdPalen** [comment]
@kshitijsalgunan script works like charm. Just download the repo and extract the `vh-script-installer` folder, past it in `/var/lib/ajenti/plugins/` and run `service ajenti restart`

**Comment by showcheap** [comment]
@kshitijsalgunan Working, but still need improved.
@LukevdPalen thanks for your test.

**Comment by kshitijsalgunan** [comment]
@showcheap and @LukevdPalen Thanks. It works.

**Pull request closed without merging**
