### PR TITLE
Fix #178

### LINKED ISSUE #178: Ajenti-v should not restart all supervisord processes at once
I have some supervisord-managed daemons which should be run uninterrupted and only restart when needed. The problem is whenever I do a changes in one of my website, all supervisord processes are restarted.

Proposed behavior: It should only restart the process that is related to the current editing website.

### PR DESCRIPTION
**Pull request by Xefir**
Fix proposed by @karbowiak, tested and worked for me.

Please see the related issue : https://github.com/ajenti/ajenti/issues/764

### CODE REVIEW

**Comment by Eugeny** [comment]
This is totally not a good idea because it doesn't take in account the webapp code that might have changed. `ajenti-ipc v apply` is typically called from CI/deployment scripts and a restart of all related processes is required to make sure that newest app version is now running.

**Comment by karbowiak** [comment]
If a config script for supervisor is changed, update will know it, and restart it.
It won't restart the already running processes that havn't changed.

Restart will restart everything, regardless of it it has changed or not. :)

**Comment by Eugeny** [comment]
Supervisor has no way of knowing if *app code* itself has been changed. And I don't mean PHP-FPM here. Think about app-server based deployments: gunicorn, puma, nodejs.

**Comment by karbowiak** [comment]
Ah yes, you're right.

Why not tie the supervisor services to the website then, and only restart those tied to it, and not every process running? :)

**Pull request closed without merging**
